[versions]
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
kotlin-poet = "1.18.0"
compile-testing = "1.6.0"
junit = "5.10.3"
kotest = "5.9.1"
kover = "0.8.1"
mockk = "1.13.11"
classgraph = "4.8.174"

[libraries]
ksp-processor = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-poet-ksp = { group ="com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet" }
kotlin-compile-testing-ksp = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version.ref = "compile-testing" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }

[plugins]
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }