[versions]
kotlin = "1.9.22"
ksp = "1.9.22-1.0.16"
kotlin-poet = "1.15.3"

[libraries]
ksp-processor = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-poet-ksp = { group ="com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet" }
