[versions]
kotlin = "1.9.22"
ksp = "1.9.22-1.0.16"
kotlin-poet = "1.15.3"
compile-testing = "1.5.0"
junit = "5.10.1"
kotest = "5.8.0"

[libraries]
ksp-processor = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlin-poet-ksp = { group ="com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet" }
kotlin-compile-testing-ksp = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version.ref = "compile-testing" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }