name: "Build and publish GitHub pages"
on:
  workflow_dispatch:
  push:
    branches:
      - feature/website

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "Set Up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 20
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew :komm-website:jsBrowserProductionWebpack
        shell: bash

      - name: "Publish"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: komm-website/build/kotlin-webpack/js/productionExecutable