name: "Build and Test"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: "Set Up JDK"
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 20
          cache: gradle

      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew

      - name: "Build with Gradle"
        run: ./gradlew build -x check
        shell: bash

      - name: "Tests"
        run: ./gradlew cleanTest allTest
        shell: bash

      - name: "Tests Report"
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: jUnit Tests
          path: '**/build/test-results/jvmTest/TEST-*.xml'
          reporter: java-junit

      - name: "Run Coverage"
        if: ${{ github.event_name == 'pull_request' }}
        run: ./gradlew koverXmlReport
        shell: bash

      - name: "Coverage Report"
        uses: mi-kas/kover-report@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: |
            ./komm-plugins-iterable/build/reports/kover/report.xml
            ./komm-processor/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Coverage Report"
          update-comment: true